---

- name: Install rvm and ruby {{ ruby_rvm_version }}
  shell: gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 && \curl -sSL https://get.rvm.io | bash -s stable --ruby={{ ruby_rvm_version }}
  args:
    creates: /usr/local/rvm/bin/rvm
    tags:
        - rvm_install
        - ruby_install

- name: Register ruby version
  shell: ruby --version | awk -F " " '{ print $2 }' | awk -F "p" '{print $1}'
  ignore_errors: True
  register: ruby_version
  tags:
    - rvm_install
    - ruby_install

- name: Register default rvm ruby destination (always changed)
  shell: readlink /usr/local/rvm/environments/default
  register: default_rvm_version
  ignore_errors: True
  tags:
    - rvm_install
    - gemset_configure

- name: Add application user to the rvm group
  user: name={{ application_user }} append=yes groups=rvm
  tags:
    - rvm_install
    - ruby_install

- name: Create rvm gemset for access (access-env)
  shell: runuser -l {{ application_user }} -c 'rvm use {{ ruby_rvm_version }} && rvm gemset create access-env'
    - rvm_install
    - gemset_configure

- name: Make access-env default gemset
  shell: runuser -l {{ application_user }} -c "rvm use {{ ruby_rvm_version }}@access-env --default"
  when: default_rvm_version.stdout != "/usr/local/rvm/environments/ruby-{{ ruby_rvm_version }}@access-env"
  tags:
    - rvm_install
    - gemset_configure

# This is why it's done this way http://stackoverflow.com/questions/22115936/install-bundler-gem-using-ansible
- name: Install bundler gem
  command: bash -lc "gem install bundler"
  become: yes
  become_user: "{{ application_user }}"
  tags:
    - base_gems_install


- name: Install passenger gem
  command: bash -lc "gem install passenger"
  become: yes
  become_user: "{{ application_user }}"
  tags:
    - passenger_gem_install

- name: install passenger dependency packages
  action: yum name={{item}} state=installed
  with_items:
    - gcc
    - gcc-c++
    - curl-devel
    - openssl-devel
    - zlib-devel
    - httpd-devel
  tags:
    - passenger_gem_install

- name: install passenger-install-apache2-module
  shell: yes '' | passenger-install-apache2-module --auto creates=/usr/local/rvm/gems/{{ruby_rvm_version}}@access-env/gems/passenger-5.0.20/buildout/apache2/mod_passenger.so
  tags:
    - passenger_apache2_module_install

- name: generate passenger.conf file
  shell: passenger-install-apache2-module --snippet > /etc/httpd/conf.d/passenger.conf
  tags:
    - generating_passenger.conf_file

- name: installing epel release
  shell: yes '' | yum install epel-release
  tags:
    - install_nodejs

- name: installing nodejs
  shell: yes '' | yum install nodejs
  tags:
    - install_nodejs

- name: changing folder permissions
  shell: chmod 1777 /tmp; chmod 0664 {{ application_path }}access/log/development.log
  tags:
    - permissions
