---

- name: Install base packages
  yum: name={{ item }} state=latest
  with_items:
      - vim
      - git
      - tar
      - sudo
      - net-tools
  tags: install_base_packages
  
- name: Create application user
  user: name={{ application_user }} system=yes
