---

- name: Install httpd
  yum: name=httpd state=latest
  tags: httpd_install

- name: Install httpd modules
  yum: name={{ item }} state=latest
  with_items:
      - mod_ssl
  tags:
    - httpd_install
    - mod_sll_install

- name: Firewall ports
  shell: firewall-cmd --permanent --add-port=80/tcp
  tags: httpd_install

- name: Firewall ports
  shell: firewall-cmd --permanent --add-port=443/tcp
  tags: httpd_install

- name: Firewall ports
  shell: firewall-cmd --reload
  tags: httpd_install
