---

- name: Create access database user
  postgresql_user: name={{ db_username }} password={{ db_password }}
  become: yes
  become_user: postgres
  tags: postgres_configure
  
- name: Enable password authentication for the new user
  lineinfile: dest=/var/lib/pgsql/data/pg_hba.conf regexp="^local(.)*{{ db_username }}(\s)*md5$"
              insertbefore="^local(.)*all(\s)*peer$"
              line="local   all             {{ db_username }}                                     md5"
              state=present
  tags: postgres_configure
  
- name: Create access application database
  postgresql_db: name={{ db_name }} encoding='UTF-8' owner={{ db_username }}
  become: yes
  become_user: postgres
  tags: postgres_configure